const jCategory =[
    {
        index: 0,
        image: "../images/google.png",
        title: "Web Developer",
        rate: "$900-1200/m",
        av: "Full Time",
        companyName: "Google",
        location: "USA",
        vacancy: "02",
        hours: "50h / week",
        description: "Designing and developing web application ,Collaborating with designers and backend developers,Ensuring cross-browser and cross-device compatibility,Writing clean, maintainable, and scalable code,Testing and debugging web applications",
        workplace: "work from home",
        Education: "Bachelor degree in any computer science course",
        Experience: " 2 to 5 year(s)",

    },
    {
        index: 1,
        image: "../images/uber.png",
        title: "Business Associate",
        rate: "$900-1200/m",
        av: "Part Time",
        companyName: "Uber",
        location: "Bangalore",
        vacancy: "25",
        hours: "8h / Day",
        description: "Uber is transforming mobility worldwide. As an Operations Manager, you’ll oversee driver-partner success and rider satisfaction in a key urban market, ensuring seamless operations.",
        workplace: "Bangalore",
        Education: "Degree",
        Experience: " 2 year(s)",
    },
    {
        index: 2,
        image: "../images/facebook.png",
        title: "Digital marketing",
        rate: "$900-1200/m",
        av: "Part Time",
        companyName: "Facebook",
        location: "Delhi",
        vacancy: "10",
        hours: "8h / Day",
        description: "At Meta, we’re building the future of connection—from VR to AI-driven communities. As a Software Engineer on our Connectivity team, you’ll design and optimize systems that bring reliable internet access to underserved regions worldwide. Think big: your code could bridge digital divides and empower millions. You’ll work with a tight-knit crew of innovators, tackling complex challenges in a collaborative, mission-driven culture. Ready to redefine how the world connects? Let’s talk.",
        workplace: "Delhi",
        Education: "Degree",
        Experience: " 2 to 3 year(s)",
    },
    {
        index: 3,
        image: "../images/linkedin.png",
        title: "Talent Acquisition Specialist",
        rate: "$900-1200/m",
        av: "Part Time",
        companyName: "Linkedin",
        location: "Chennai",
        vacancy: "25",
        hours: "8h / Day",
        description: "Manage the recruitment process for various roles within LinkedIn, from sourcing to hiring.,Collaborate with hiring managers to understand their staffing needs and job requirements.,Develop sourcing strategies to attract top talent via LinkedIn, job boards, and social media.Screen resumes and conduct initial candidate interviews to assess qualifications.Coordinate interviews and facilitate communication between candidates and hiring managers.Maintain an organized pipeline of potential candidates and manage candidate experience throughout the recruitment process.Provide hiring managers with market insights, compensation benchmarks, and talent availability.",
        workplace: "Chennai",
        Education: "Degree",
        Experience: " 2 year(s)",
    },
    {
        index: 4,
        image: "../images/instagram.png",
        title: "Social Media Manager",
        rate: "$900-1200/m",
        av: "Freelancer",
        companyName: "Instagram",
        location: "Andhra pradesh",
        vacancy: "46",
        hours: "8h / Day",
        description: "Develop and execute social media strategies to increase brand awareness and engagement on Instagram.Create and curate high-quality content (photos, videos, and graphics).Engage with followers and respond to direct messages and comments.Collaborate with influencers and partners to create co-branded campaigns.Monitor social media trends and provide insights to improve performance.Analyze and report on key metrics to improve content and engagement strategies.",
        workplace: "Bangalore",
        Education: "Degree",
        Experience: " 1 year(s)",
    },
    {
        index: 5,
        image: "../images/yahoo.png",
        title: "Data Scientist",
        rate: "$900-1200/m",
        av: "Full Time",
        companyName: "Yahoo",
        location: "Telangana",
        vacancy: "05",
        hours: "8h / Day",
        description: "Uber is transforming mobility worldwide. As an Operations Manager, you’ll oversee driver-partner success and rider satisfaction in a key urban market, ensuring seamless operations.",
        workplace: "Telangana",
        Education: "Degree",
        Experience: " 3 year(s)",
    },
    {
        index: 6,
        image: "../images/apple.png",
        title: "Web Developer",
        rate: "$900-1200/m",
        av: "Full time",
        companyName: "Apple",
        location: "USA",
        vacancy: "25",
        hours: "8h / Day",
        description: "As a Full Stack Web Developer at Apple, you will lead the architecture, design, and development of robust full-stack solutions. Your role will involve collaborating with product managers, designers, and other partners to understand project requirements, mentoring junior developers, and participating in code reviews to maintain code quality. Preferred qualifications include experience in web analytics, accessibility, standards, and security, as well as familiarity with containerization and orchestration technologies like Docker and Kubernetes.",
        workplace: "USA",
        Education: "Degree",
        Experience: " 5 year(s)",
    },
];